import { z } from 'zod'

export const ClientSchema = z.object({
	id: z.uuid().optional(), // generated by db
	orgId: z.string().max(255).optional(),
	name: z.string().min(1, 'Name is required'),
	email: z.email('Invalid email').optional(),
	phone: z
		.string()
		.regex(
			/^\d{3}-\d{3}-\d{4}$/,
			'Phone number must be formatted as 123-123-1234',
		)
		.optional(),
	address: z.string().optional().or(z.literal('')),
	createdAt: z.date().optional(),
})

export type Client = z.infer<typeof ClientSchema>
export type ClientFormValues = z.infer<typeof ClientSchema>

export const ProductSchema = z.object({
  id: z.uuid().optional(), // generated by db
  orgId: z.string().max(255).optional(),
  name: z.string().min(1, "Name is required"),
  description: z.string().optional().or(z.literal("")),
  price: z.string().min(1, "Price is required"),
  sku: z.string().optional().or(z.literal("")),
  createdAt: z.date().optional(),
});

export type Product = z.infer<typeof ProductSchema>;
export type ProductFormValues = z.infer<typeof ProductSchema>;

export const createProductsTableSql = `
CREATE TABLE IF NOT EXISTS products (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id VARCHAR(255) NOT NULL, 
  email VARCHAR(255),
  name VARCHAR(255) NOT NULL,
  description TEXT,
  price NUMERIC(10, 2) NOT NULL,
  sku VARCHAR(100),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
`
