import { z } from "zod";

export const ClientSchema = z.object({
  id: z.uuid().optional(), // generated by db
  name: z.string().min(1, "Name is required"),
  email: z.email("Invalid email").optional().or(z.literal("")),
  phone: z.string().optional().or(z.literal("")),
  address: z.string().optional().or(z.literal("")),
  createdAt: z.date().optional(),
});

export type Client = z.infer<typeof ClientSchema>;
export type ClientFormValues = z.infer<typeof ClientSchema>;

// // Raw SQL query to create the schema in Neon
// export const createClientsTableSql = `
// CREATE TABLE IF NOT EXISTS clients (
//   id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
//   name VARCHAR(255) NOT NULL,
//   email VARCHAR(255),
//   phone VARCHAR(50),
//   address TEXT,
//   created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
// );
// `;
