import { z } from "zod";

export const ClientSchema = z.object({
  id: z.uuid().optional(), // generated by db
  name: z.string().min(1, "Name is required"),
  email: z.email("Invalid email").optional(),
  phone: z
    .string()
    .regex(
      /^\d{3}-\d{3}-\d{4}$/,
      "Phone number must be formatted as 123-123-1234",
    )
    .optional(),
  address: z.string().optional().or(z.literal("")),
  createdAt: z.date().optional(),
});

export type Client = z.infer<typeof ClientSchema>;
export type ClientFormValues = z.infer<typeof ClientSchema>;

// // Raw SQL query to create the schema in Neon
export const createClientsTableSql = `
CREATE TABLE IF NOT EXISTS clients (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255),
  phone VARCHAR(50),
  address TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
`;

export const ProductSchema = z.object({
  id: z.uuid().optional(), // generated by db
  name: z.string().min(1, "Name is required"),
  description: z.string().optional().or(z.literal("")),
  price: z.string().min(1, "Price is required"),
  sku: z.string().optional().or(z.literal("")),
  createdAt: z.date().optional(),
});

export type Product = z.infer<typeof ProductSchema>;
export type ProductFormValues = z.infer<typeof ProductSchema>;

export const createProductsTableSql = `


`;
